### ISSUE TITLE
FileNaming :/

### ISSUE THREAD

**Issue by RafaelMorenoSteenwinckel** [LasCC/Hack-Tools#114]
Un fichier infecté a tenté de s'exécuter sur votre appareil.
Nom de la menace: Heur.BZC.PZQ.Boxter.6009.024F0EB9
Chemin : /Users/rafaelmoreno/Anytime/Hack-Tools/src/components/linux/ReverseShell.tsx
Nous avons effacé ce fichier en quarantaine pour éviter que des commandes malveillantes soient exécutées sur votre appareil.

**Comment by rb-x** [comment]
Salut, il s'agit d'un faux positif, la détection est principalement causée par les chaines de caractères liés au  webshell en php.
