### ISSUE TITLE
SQLi Column name enumeration for Oracle has a pottential typo?

### ISSUE THREAD

**Issue by yigitemres** [LasCC/Hack-Tools#120]
`' UNION SELECT column_name,NULL FROM  where table_name="X"  -- -` should be `' UNION SELECT column_name,NULL FROM all_tab_columns where table_name="X"  -- -`

**Comment by rb-x** [comment]
Thanks, it has been fixed in https://github.com/LasCC/Hack-Tools/commit/368c3f9be5fc7bd7953ba6fec0ce919f7080bbbc
