### ISSUE TITLE
Bug report - Commas appear between values when copying to clipboard in MSF Venom Builder

### ISSUE THREAD

**Issue by asherXt** [LasCC/Hack-Tools#132]
Hello,

I would like to report a bug in the MSF Venom Builder. When copying the generated payload to the clipboard, commas appear between each value, which can cause issues when trying to use the payload in other tools or scripts.

Steps to reproduce:

1)   Launch the MSF Venom Builder.
2)   Select the desired payload and options.
3)   Click the "Copy to Clipboard" button for msf venom command.
4)   Paste the clipboard contents into a text editor or other tool.

Expected result:
The generated payload should be copied to the clipboard without any extra characters or formatting.

Actual result:
Commas appear between each value of the generated payload when it is copied to the clipboard.

This bug can be frustrating and time-consuming to work around, and I would appreciate it if the developers could investigate and fix the issue as soon as possible.

Thank you for your attention to this matter.

**Comment by LasCC** [comment]
Hello @asherXt,

Thank you for taking the time to report the bug. We have fixed the issue in our latest release, and you can find the commit with the fix at this link: https://github.com/LasCC/Hack-Tools/pull/133/commits/6f64b1f93f8f90ed1dd94b8c1556ef5dd99f3055
