### ISSUE TITLE
npm ERR

### ISSUE THREAD

**Issue by sara-caballero** [LasCC/Hack-Tools#134]
$ npm install && npm run build
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: hack-tools@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from @hot-loader/react-dom@17.0.2
npm ERR! node_modules/@hot-loader/react-dom
npm ERR!   @hot-loader/react-dom@"^17.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by rb-x** [comment]
Hi,
Could you please provide additional information about your system / node version / npm version?
I would suggest cleaning already existent node_modules and retrying with yarn or pnpm.

If none of this works, use the precompiled version in the releases.
