### ISSUE TITLE
Firefox: version on addons.mozilla.org is still 0.4.0 while 0.5.0 is released

### ISSUE THREAD

**Issue by sysms** [LasCC/Hack-Tools#150]
Dear DEVs,

thank you for this great and useful extension!

The version on addons.mozilla.org is still at 0.4..0, while 0.5.0 is available as release here.

Am I missing something? :)

**Comment by rb-x** [comment]
Thanks for using our extension, and I appreciate your support! I'm pretty sure I've pushed version 0.5.0 months ago. I'll look into what might be happening on the Mozilla store's side.

**Comment by sysms** [comment]
> I'll look into what might be happening on the Mozilla store's side.

Do you have any idea, what's going on?

BTW: I'm using Firefox 115.4esr on up-to-date Kali Linux, if that matters...?!

**Comment by Ilyesdhiaeddine** [comment]
Same problem here it was up-to-date on an older VM I had, but now only the 0.4.0 version is available on the Mozilla store.
maybe you can push it to the store again.

> Thanks for using our extension, and I appreciate your support! I'm pretty sure I've pushed version 0.5.0 months ago. I'll look into what might be happening on the Mozilla store's side.

but this solves the issue temporarily
>Or install it as a temporary plugin in Firefox in the page about:debugging#/runtime/this-firefox by selecting the manifest inside dist

**Comment by LasCC** [comment]
Hello everyone! 

Thanks for highlighting this issue. We've identified the mismatch in the Mozilla store and have made the decision to directly ship our upcoming major update instead, the version **0.5.0**. 

[Click here to see the changes on the dev branch](https://github.com/LasCC/HackTools/tree/dev)

Stay tuned for the exciting new release, and thanks again for your understanding!

**Comment by SecBurg** [comment]
Is this extension for Firefox still in development?

**Comment by rb-x** [comment]
Hi, unfortunately, there is a size limitation for Firefox extensions, which must not exceed 5MB.
Due to this constraint, we have had to pause the development of the HackTools extension for firefox.
Therefore, we recommend using the online version of it available at hacktools.sh or running it on your own as a web application.

**Comment by Lamisedaxeh** [comment]
Hello,
Sad to see the dev stopped for Firefox. A permission in the manifest.json appears to exist to extend the storage of an add-on:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#unlimited_storage
